### ISSUE TITLE
Need more information about MB configurations

### ISSUE THREAD

**Issue by Schljk3bnz69** [wso2/docs-ei#1048]
Location : https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/tutorials/storing-and-forwarding-messages/

I followed the tutorial, with a fresh instalation of the wso2ei 7.0.1 and mb 3.2.0 and got this error

> ERROR {org.apache.axis2.transport.jms.JMSConnectionFactoryManager} - Error setting up connection factory : myQueueSender org.apache.axis2.transport.jms.AxisJMSException: Cannot acquire JNDI context, JMS Connection factory : QueueConnectionFactory or default destination : null for JMS CF : myQueueSender using : {transport.jms.CacheLevel=producer, broker_name=wso2mb, transport.jms.ConnectionFactoryType=queue, java.naming.factory.initial=org.wso2.andes.jndi.PropertiesFileInitialContextFactory, transport.jms.ConnectionFactoryJNDIName=QueueConnectionFactory, java.naming.provider.url=conf/jndi.properties}
        at org.apache.axis2.transport.jms.JMSConnectionFactory.initJMSConnectionFactory(JMSConnectionFactory.java:188)
        at org.apache.axis2.transport.jms.JMSConnectionFactory.<init>(JMSConnectionFactory.java:152)
        at org.apache.axis2.transport.jms.JMSConnectionFactoryManager.loadConnectionFactoryDefinitions(JMSConnectionFactoryManager.java:89)
        at org.apache.axis2.transport.jms.JMSConnectionFactoryManager.<init>(JMSConnectionFactoryManager.java:76)
        at org.apache.axis2.transport.jms.JMSSender.init(JMSSender.java:85)
        at org.apache.axis2.context.ConfigurationContextFactory.initTransportSenders(ConfigurationContextFactory.java:300)
        at org.apache.axis2.context.ConfigurationContextFactory.init(ConfigurationContextFactory.java:231)
        at org.apache.axis2.context.ConfigurationContextFactory.createConfigurationContext(ConfigurationContextFactory.java:93)
        at org.wso2.micro.core.CarbonConfigurationContextFactory.createNewConfigurationContext(CarbonConfigurationContextFactory.java:66)
        at org.wso2.micro.integrator.core.internal.CoreServerInitializer.initializeCarbon(CoreServerInitializer.java:211)
        at org.wso2.micro.integrator.core.internal.CoreServerInitializer.initMIServer(CoreServerInitializer.java:128)
        at org.wso2.micro.integrator.core.internal.Activator.start(Activator.java:82)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
        at org.eclipse.osgi.container.Module.doStart(Module.java:598)
        at org.eclipse.osgi.container.Module.start(Module.java:462)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: javax.naming.NameNotFoundException: QueueConnectionFactory
        at org.wso2.andes.jndi.ReadOnlyContext.lookup(ReadOnlyContext.java:271)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at org.apache.axis2.transport.jms.JMSUtils.lookup(JMSUtils.java:741)
        at org.apache.axis2.transport.jms.JMSConnectionFactory.initJMSConnectionFactory(JMSConnectionFactory.java:175)
        ... 29 more

>[2019-12-04 15:11:13,749]  INFO {org.apache.axis2.transport.jms.JMSSender} - JMS Transport Sender initialized...
[2019-12-04 15:11:15,138] ERROR {org.apache.axis2.transport.jms.JMSConnectionFactoryManager} - Error setting up connection factory : myQueueListener org.apache.axis2.transport.jms.AxisJMSException: Cannot acquire JNDI context, JMS Connection factory : QueueConnectionFactory or default destination : null for JMS CF : myQueueListener using : {transport.jms.CacheLevel=consumer, broker_name=wso2mb, transport.jms.ConnectionFactoryType=queue, java.naming.factory.initial=org.wso2.andes.jndi.PropertiesFileInitialContextFactory, transport.jms.ConnectionFactoryJNDIName=QueueConnectionFactory, java.naming.provider.url=conf/jndi.properties}
        at org.apache.axis2.transport.jms.JMSConnectionFactory.initJMSConnectionFactory(JMSConnectionFactory.java:188)
        at org.apache.axis2.transport.jms.JMSConnectionFactory.<init>(JMSConnectionFactory.java:152)
        at org.apache.axis2.transport.jms.JMSConnectionFactoryManager.loadConnectionFactoryDefinitions(JMSConnectionFactoryManager.java:89)
        at org.apache.axis2.transport.jms.JMSConnectionFactoryManager.<init>(JMSConnectionFactoryManager.java:76)
        at org.apache.axis2.transport.jms.JMSListener.doInit(JMSListener.java:70)
        at org.apache.axis2.transport.base.AbstractTransportListenerEx.init(AbstractTransportListenerEx.java:62)
        at org.apache.axis2.engine.ListenerManager.init(ListenerManager.java:84)
        at org.wso2.micro.integrator.core.internal.CoreServerInitializer.initializeCarbon(CoreServerInitializer.java:222)
        at org.wso2.micro.integrator.core.internal.CoreServerInitializer.initMIServer(CoreServerInitializer.java:128)
        at org.wso2.micro.integrator.core.internal.Activator.start(Activator.java:82)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
        at org.eclipse.osgi.container.Module.doStart(Module.java:598)
        at org.eclipse.osgi.container.Module.start(Module.java:462)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: javax.naming.NameNotFoundException: QueueConnectionFactory
        at org.wso2.andes.jndi.ReadOnlyContext.lookup(ReadOnlyContext.java:271)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at org.apache.axis2.transport.jms.JMSUtils.lookup(JMSUtils.java:741)
        at org.apache.axis2.transport.jms.JMSConnectionFactory.initJMSConnectionFactory(JMSConnectionFactory.java:175)
        ... 27 more

[2019-12-04 15:11:15,141]  INFO {org.apache.axis2.transport.jms.JMSListener} - JMS Transport Receiver/Listener initialized...

is this a issue? I don't know but I followed the whole tutorial until this step and I cant move on.....

**Comment by rsdickerson** [comment]
I am encountering this same error. MB Configurations? I didn't make any changes to the OOTB MB. Just downloaded and started it.
The tutorial details all the steps to setup the JMS listener and sender.

[Asynchronous Messaging](https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/tutorials/storing-and-forwarding-messages/)

**Comment by rsdickerson** [comment]
Also, is the MB port wrong in the tutorial?

amqp://admin:admin@clientID/carbon?brokerlist='tcp://localhost:5675'

MB is listening on 5672.

**Comment by nilminiwso2** [comment]
Hi,
We are checking on this..
Thank you.

**Comment by rsdickerson** [comment]
Thanks. I tried using the pre-packaged version of the project (from [here](https://github.com/wso2-docs/WSO2_EI/blob/master/Integration-Tutorial-Artifacts/StoreAndForwardTutorial.zip)). Opened it in Integration Studio, <right click> SampleServicesCompositeApplication and selected Export Project Artifacts and Run. 
I get the following exception:

> [2020-02-27 22:23:13,876] ERROR {org.apache.axis2.transport.jms.JMSConnectionFactoryManager} - Error setting up connection factory : myQueueSender org.apache.axis2.transport.jms.AxisJMSException: Cannot acquire JNDI context, JMS Connection factory : QueueConnectionFactory or default destination : null for JMS CF : myQueueSender using : {transport.jms.CacheLevel=producer, broker_name=wso2mb, transport.jms.ConnectionFactoryType=queue, java.naming.factory.initial=org.wso2.andes.jndi.PropertiesFileInitialContextFactory, transport.jms.ConnectionFactoryJNDIName=QueueConnectionFactory, java.naming.provider.url=conf/jndi.properties}

I also tried Export Composite Application Project to Enterprise Integrator and got the same exception.

**Comment by sdkottegoda** [comment]
The issue has been due to the incorrect configurations provided in the documentation. We have fixed them by https://github.com/wso2/docs-ei/pull/1203. Thank you very much for reporting the issue.

**Comment by sdkottegoda** [comment]
> Also, is the MB port wrong in the tutorial?
> 
> amqp://admin:admin@clientID/carbon?brokerlist='tcp://localhost:5675'
> 
> MB is listening on 5672.

@rsdickerson The documentation refers to the broker profile of WSO2EI which comes with a default port offset of 3, hence the AMQP port of 5675. We will improve the clarity on the documenation regarding this.

**Comment by nilminiwso2** [comment]
We have done the documentation updates to improve the content: https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/tutorials/storing-and-forwarding-messages/

Thanks for reaching out to us!
