### ISSUE TITLE
The sample file from Quick Start Guide does not run

### ISSUE THREAD

**Issue by sjacek** [wso2/docs-ei#2684]
**Description:**
Guick Start Guide contains samples MI_QSG_HOME-JDK11 which contains backend DoctorInfo-JDK11.jar.
The guide says to use the following command to start the services
`java -jar DoctorInfo-JDK11.jar`

It does not run but finishes with a following message

```
2021-01-08 16:59:51 INFO  MicroservicesRegistry:55 - Added microservice: org.wso2.service.hospital.GrandOakDoctorInfoService@75412c2f
2021-01-08 16:59:51 INFO  MicroservicesRegistry:55 - Added microservice: org.wso2.service.hospital.PineValleyDoctorInfoService@282ba1e
2021-01-08 16:59:51 INFO  MicroservicesRegistry:55 - Added microservice: org.wso2.msf4j.internal.swagger.SwaggerDefinitionService@12843fce
2021-01-08 16:59:51 INFO  NettyListener:68 - Starting Netty Http Transport Listener
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.PlatformDependent0 (file:/home/jacek/Projekty/wso2/MI_QSG_HOME/Backend/DoctorInfo-JDK11.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.PlatformDependent0
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-01-08 16:59:51 INFO  PlatformDependent:101 - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
Exception in thread "main" java.net.BindException: Adres jest już w użyciu
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:455)
        at java.base/sun.nio.ch.Net.bind(Net.java:447)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:485)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1089)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:430)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:415)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:903)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:198)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:348)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:356)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
Linux Mint 20, CentOS 8

**Steps to reproduce:**
Start backend service according to this [https://ei.docs.wso2.com/en/latest/micro-integrator/overview/quick-start-guide/#start-back-end-services](https://ei.docs.wso2.com/en/latest/micro-integrator/overview/quick-start-guide/#start-back-end-services)

**Related Issues:**

**Comment by sjacek** [comment]
DoctorInfo-JDK11.jar tries to open port 9090.  Linux Mint and CentOS have a web console on that port.
It's recommended to change the port in the samples.
