### ISSUE TITLE
Doc Feedback: "cacheableDuration" and "engineVersion" under [[external_vault]] configs should be string values

### ISSUE THREAD

**Issue by Thidasala** [wso2/docs-ei#2904]
Location : https://ei.docs.wso2.com/en/7.2.0/micro-integrator/setup/security/using-hashicorp-secrets/

[[external_vault]] configurations should be modified as below:

name = "hashicorp"
address = "http://127.0.0.1:8200"
rootToken = "ROOT_TOKEN"
roleId = "ROLE_ID"
secretId = "SECRET_ID"
**cacheableDuration = "15000"
engineVersion = "2"**
namespace = "NAMESPACE"
trustStoreFile = "${carbon.home}/repository/resources/security/client-truststore.jks"
keyStoreFile = "${carbon.home}/repository/resources/security/wso2carbon.jks"
keyStorePassword = "KEY_STORE_PASSWORD"

otherwise following error is displayed after the configurations:

```
[2022-09-06 16:39:02,351] ERROR {SynapseXPath} - Evaluation of the XPath expression hashicorp:vault-lookup('secret/creds', 'passcode') resulted in an error org.jaxen.FunctionCallException: Error while initializing the secure vault configs
	at org.wso2.micro.integrator.mediation.security.vault.external.hashicorp.HashiCorpVaultLookupFunction.call(HashiCorpVaultLookupFunction.java:101)
	at org.jaxen.expr.DefaultFunctionCallExpr.evaluate(DefaultFunctionCallExpr.java:181)
	at org.jaxen.expr.DefaultXPathExpr.asList(DefaultXPathExpr.java:102)
	at org.jaxen.BaseXPath.selectNodesForContext(BaseXPath.java:675)
	at org.jaxen.BaseXPath.selectNodes(BaseXPath.java:215)
	at org.jaxen.BaseXPath.evaluate(BaseXPath.java:175)
	at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:411)
	at org.apache.synapse.mediators.builtin.PropertyMediator.getResultValue(PropertyMediator.java:410)
	at org.apache.synapse.mediators.builtin.PropertyMediator.mediate(PropertyMediator.java:133)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.api.Resource.process(Resource.java:342)
	at org.apache.synapse.api.API.process(API.java:463)
	at org.apache.synapse.api.AbstractApiHandler.apiProcess(AbstractApiHandler.java:93)
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:71)
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:84)
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:70)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:375)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:189)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.micro.integrator.mediation.security.vault.external.ExternalVaultException: Error while initializing the secure vault configs
	at org.wso2.micro.integrator.mediation.security.vault.external.hashicorp.HashiCorpVaultLookupHandlerImpl.<init>(HashiCorpVaultLookupHandlerImpl.java:89)
	at org.wso2.micro.integrator.mediation.security.vault.external.hashicorp.HashiCorpVaultLookupHandlerImpl.getDefaultSecurityService(HashiCorpVaultLookupHandlerImpl.java:95)
	at org.wso2.micro.integrator.mediation.security.vault.external.hashicorp.HashiCorpVaultLookupFunction.call(HashiCorpVaultLookupFunction.java:98)
	... 27 more
Caused by: org.wso2.micro.integrator.mediation.security.vault.external.ExternalVaultException: Error while connecting the HashiCorp vault
	at org.wso2.micro.integrator.mediation.security.vault.external.hashicorp.HashiCorpVaultLookupHandlerImpl.initialize(HashiCorpVaultLookupHandlerImpl.java:144)
	at org.wso2.micro.integrator.mediation.security.vault.external.hashicorp.HashiCorpVaultLookupHandlerImpl.<init>(HashiCorpVaultLookupHandlerImpl.java:87)
	... 29 more
Caused by: com.bettercloud.vault.VaultException: Error while generating a new client token using the roleId and secretId. Please check the secret_id_num_uses parameter value for the troubleshooting purposes.
	at org.wso2.micro.integrator.mediation.security.vault.external.hashicorp.HashiCorpVaultLookupHandlerImpl.authenticateHashiCorpVault(HashiCorpVaultLookupHandlerImpl.java:162)
	at org.wso2.micro.integrator.mediation.security.vault.external.hashicorp.HashiCorpVaultLookupHandlerImpl.initialize(HashiCorpVaultLookupHandlerImpl.java:133)
	... 30 more
```

**Comment by chanikag** [comment]
Fixed in MI docs https://mi.docs.wso2.com/en/latest/install-and-setup/setup/security/using-hashicorp-secrets/#connecting-mi-to-the-hashicorp-server
